export const SET_INDEX_SEARCH_INFO = 'base/SET_INDEX_SEARCH_INFO'
export const SET_QUYU_LIST = 'base/SET_QUYU_LIST'
export const SET_DITIE_LIST = 'base/SET_DITIE_LIST'
export const SET_TYPE_LIST = 'base/SET_TYPE_LIST'
export const SET_MAP_LIST = 'base/SET_MAP_LIST'
export const SET_TESE_LIST = 'base/SET_TESE_LIST'
export const SET_HUXING_LIST = 'base/SET_HUXING_LIST'
export const SET_HUANXIAN_LIST = 'base/SET_HUANXIAN_LIST'